import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../models/daily_report.dart';

class DailyReportPdfService {
  static final _money = NumberFormat.decimalPattern();
  static final _fullDate = DateFormat('EEEE, d MMMM yyyy');
  static final _dateTime = DateFormat('d MMM yyyy, h:mm a');
  static final _time = DateFormat('HH:mm');

  /// Builds the PDF and opens the OS's native print/share preview -
  /// the one shared entry point both the report detail screen and the
  /// main View Reports screen use, so the Printing.layoutPdf() call
  /// only needs to live in one place.
  static Future<void> printOrDownload(DailyReport report, {required String facilityName}) async {
    final doc = await build(report, facilityName: facilityName);
    await Printing.layoutPdf(
      onLayout: (format) => doc.save(),
      name: 'daily-closing-report-${report.id}.pdf',
    );
  }

  static final _deepGreen = PdfColor.fromInt(0xFF2F5D62);
  static final _red = PdfColor.fromInt(0xFFC62828);
  static final _green = PdfColor.fromInt(0xFF2E7D32);
  static final _grey = PdfColor.fromInt(0xFF616161);
  static final _lightGrey = PdfColor.fromInt(0xFFE0E0E0);

  /// Builds the full report document - a standard A4 page, sized and
  /// spaced for an actual physical printout, not just an on-screen
  /// export: consistent header/footer on every page (so a page can be
  /// identified if separated from the rest), page numbers, and status
  /// always carried in text as well as color, since many office and
  /// shop printers are grayscale.
  static Future<pw.Document> build(DailyReport report, {required String facilityName}) async {
    final doc = pw.Document();

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.fromLTRB(32, 28, 32, 28),
        header: (context) => _pageHeader(facilityName, report, context.pageNumber, context.pagesCount),
        footer: (context) => _pageFooter(context.pageNumber, context.pagesCount),
        build: (context) => [
          _titleBlock(report, facilityName),
          pw.SizedBox(height: 16),
          _summarySection(report),
          pw.SizedBox(height: 14),
          _salesSection(report),
          pw.SizedBox(height: 14),
          _servicesSection(report),
          pw.SizedBox(height: 14),
          _paymentMethodsSection(report),
          pw.SizedBox(height: 14),
          _productMovementSection(report),
          pw.SizedBox(height: 14),
          _stockReconciliationSection(report),
          pw.SizedBox(height: 14),
          _debtSection(report),
          pw.SizedBox(height: 14),
          _expensesSection(report),
          pw.SizedBox(height: 14),
          _paymentReconciliationSection(report),
          pw.SizedBox(height: 14),
          _declarationSection(report),
          pw.SizedBox(height: 18),
          _signOffSection(report),
        ],
      ),
    );

    return doc;
  }

  // ---------- Header / footer (repeated every page) ----------

  static pw.Widget _pageHeader(String facilityName, DailyReport report, int pageNumber, int pagesCount) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 8),
      decoration: const pw.BoxDecoration(border: pw.Border(bottom: pw.BorderSide(color: PdfColors.grey300, width: 0.75))),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text('VetBiz Pro - Daily Closing Report',
              style: pw.TextStyle(fontSize: 9, color: _grey, fontWeight: pw.FontWeight.bold)),
          pw.Text('$facilityName - ${_fullDate.format(report.reportDate)}  |  Page $pageNumber of $pagesCount',
              style: pw.TextStyle(fontSize: 9, color: _grey)),
        ],
      ),
    );
  }

  static pw.Widget _pageFooter(int pageNumber, int pagesCount) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(top: 6),
      decoration: const pw.BoxDecoration(border: pw.Border(top: pw.BorderSide(color: PdfColors.grey300, width: 0.75))),
      child: pw.Text('Generated by VetBiz Pro', style: pw.TextStyle(fontSize: 8, color: PdfColors.grey500)),
    );
  }

  // ---------- Title block ----------

  static pw.Widget _titleBlock(DailyReport report, String facilityName) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text('Daily Closing Report', style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold, color: _deepGreen)),
        pw.SizedBox(height: 6),
        _kv('Facility', facilityName),
        _kv('Date', _fullDate.format(report.reportDate)),
        _kv('Staff', report.generatedByName),
        _kv('Status', report.status == 'submitted' ? 'Submitted' : 'Draft - not yet submitted'),
      ],
    );
  }

  static pw.Widget _kv(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 1.5),
      child: pw.Row(
        children: [
          pw.SizedBox(width: 70, child: pw.Text(label, style: pw.TextStyle(fontSize: 10.5, color: _grey))),
          pw.Text(value, style: pw.TextStyle(fontSize: 10.5, fontWeight: pw.FontWeight.bold)),
        ],
      ),
    );
  }

  // ---------- Shared section helpers ----------

  static pw.Widget _sectionTitle(String title) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 4),
      margin: const pw.EdgeInsets.only(bottom: 6),
      decoration: pw.BoxDecoration(border: pw.Border(bottom: pw.BorderSide(color: _deepGreen, width: 1))),
      child: pw.Text(title, style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold, color: _deepGreen)),
    );
  }

  static pw.Widget _statLine(String label, String value, {bool bold = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 2),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label, style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey800)),
          pw.Text(value, style: pw.TextStyle(fontSize: 10, fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal)),
        ],
      ),
    );
  }

  static pw.Widget _table(List<String> headers, List<List<String>> rows, {List<int>? flex}) {
    return pw.Table(
      border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
      columnWidths: flex != null
          ? {for (var i = 0; i < flex.length; i++) i: pw.FlexColumnWidth(flex[i].toDouble())}
          : null,
      children: [
        pw.TableRow(
          decoration: pw.BoxDecoration(color: _lightGrey),
          children: headers
              .map((h) => pw.Padding(
                    padding: const pw.EdgeInsets.symmetric(horizontal: 5, vertical: 4),
                    child: pw.Text(h, style: pw.TextStyle(fontSize: 8.5, fontWeight: pw.FontWeight.bold)),
                  ))
              .toList(),
        ),
        for (final row in rows)
          pw.TableRow(
            children: row
                .map((cell) => pw.Padding(
                      padding: const pw.EdgeInsets.symmetric(horizontal: 5, vertical: 3.5),
                      child: pw.Text(cell, style: const pw.TextStyle(fontSize: 9)),
                    ))
                .toList(),
          ),
      ],
    );
  }

  static pw.Widget _emptyNote(String text) =>
      pw.Padding(padding: const pw.EdgeInsets.symmetric(vertical: 4), child: pw.Text(text, style: pw.TextStyle(fontSize: 9.5, color: _grey, fontStyle: pw.FontStyle.italic)));

  // ---------- Sections ----------

  static pw.Widget _summarySection(DailyReport report) {
    final revenue = report.salesTotalValue + report.servicesTotalValue + report.totalOtherIncome;
    final totalCash = (report.salesByPaymentMethod['Cash'] ?? 0) +
        (report.servicesByPaymentMethod['Cash'] ?? 0) +
        (report.repaymentsByPaymentMethod['Cash'] ?? 0) +
        (report.otherIncomeByPaymentMethod['Cash'] ?? 0);
    final productsSoldUnits = report.productMovement.fold(0, (sum, p) => sum + p.sold);

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('Daily Summary'),
        pw.Wrap(
          spacing: 24,
          runSpacing: 4,
          children: [
            pw.SizedBox(width: 230, child: _statLine('Total Sales', 'Tsh ${_money.format(report.salesTotalValue)}', bold: true)),
            pw.SizedBox(width: 230, child: _statLine('Service Revenue', 'Tsh ${_money.format(report.servicesTotalValue)}', bold: true)),
            pw.SizedBox(width: 230, child: _statLine('Total Revenue', 'Tsh ${_money.format(revenue)}', bold: true)),
            if (report.totalOtherIncome > 0)
              pw.SizedBox(width: 230, child: _statLine('Other Income', 'Tsh ${_money.format(report.totalOtherIncome)}')),
            pw.SizedBox(width: 230, child: _statLine('Debt Repayments', 'Tsh ${_money.format(report.repaymentsValue)}')),
            pw.SizedBox(width: 230, child: _statLine('Expenses', 'Tsh ${_money.format(report.totalExpenses)}')),
            pw.SizedBox(width: 230, child: _statLine('Total Cash Received', 'Tsh ${_money.format(totalCash)}')),
            pw.SizedBox(width: 230, child: _statLine('New Debt Today', 'Tsh ${_money.format(report.newDebtValue)}')),
            pw.SizedBox(width: 230, child: _statLine('Transactions', '${report.salesCount + report.servicesCount}')),
            pw.SizedBox(width: 230, child: _statLine('Products Sold', '$productsSoldUnits units')),
          ],
        ),
      ],
    );
  }

  static pw.Widget _salesSection(DailyReport report) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('Sales'),
        if (report.salesLineItems.isEmpty)
          _emptyNote('No sales recorded today.')
        else ...[
          _table(
            ['Time', 'Receipt', 'Customer', 'Items', 'Amount', 'Payment'],
            report.salesLineItems
                .map((s) => [
                      _time.format(s.time),
                      s.receiptNo,
                      s.customerName,
                      '${s.itemCount}',
                      _money.format(s.amount),
                      s.paymentMethod,
                    ])
                .toList(),
            flex: [2, 2, 3, 1, 2, 2],
          ),
          pw.SizedBox(height: 6),
          _statLine('Total Sales', 'Tsh ${_money.format(report.salesTotalValue)}', bold: true),
          if (report.salesByPaymentMethod.isNotEmpty)
            pw.Padding(
              padding: const pw.EdgeInsets.only(top: 4),
              child: pw.Wrap(
                spacing: 24,
                children: report.salesByPaymentMethod.entries
                    .map((e) => pw.Text('${e.key}: Tsh ${_money.format(e.value)}', style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700)))
                    .toList(),
              ),
            ),
        ],
      ],
    );
  }

  static pw.Widget _servicesSection(DailyReport report) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('Veterinary Services'),
        if (report.serviceBreakdown.isEmpty)
          _emptyNote('No services provided today.')
        else ...[
          _table(
            ['Service', 'Number', 'Revenue'],
            report.serviceBreakdown.map((s) => [s.serviceName, '${s.count}', _money.format(s.revenue)]).toList(),
            flex: [4, 2, 2],
          ),
          pw.SizedBox(height: 6),
          _statLine('Total Service Revenue', 'Tsh ${_money.format(report.servicesTotalValue)}', bold: true),
        ],
      ],
    );
  }

  static pw.Widget _paymentMethodsSection(DailyReport report) {
    final combined = <String, double>{};
    for (final entry in report.salesByPaymentMethod.entries) {
      combined[entry.key] = (combined[entry.key] ?? 0) + entry.value;
    }
    for (final entry in report.servicesByPaymentMethod.entries) {
      combined[entry.key] = (combined[entry.key] ?? 0) + entry.value;
    }
    for (final entry in report.repaymentsByPaymentMethod.entries) {
      combined[entry.key] = (combined[entry.key] ?? 0) + entry.value;
    }
    for (final entry in report.otherIncomeByPaymentMethod.entries) {
      combined[entry.key] = (combined[entry.key] ?? 0) + entry.value;
    }
    final combinedTotal = combined.values.fold(0.0, (sum, v) => sum + v);

    if (combined.isEmpty) {
      return pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          _sectionTitle('Payment Methods'),
          _emptyNote('No payments recorded today.'),
        ],
      );
    }

    pw.Widget categoryColumn(String title, Map<String, double> byMethod, String emptyText) {
      return pw.Expanded(
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(title, style: pw.TextStyle(fontSize: 10.5, fontWeight: pw.FontWeight.bold, color: _deepGreen)),
            pw.SizedBox(height: 4),
            if (byMethod.isEmpty)
              _emptyNote(emptyText)
            else
              _table(
                ['Method', 'Amount'],
                byMethod.entries.map((e) => [e.key, _money.format(e.value)]).toList(),
                flex: [3, 2],
              ),
          ],
        ),
      );
    }

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('Payment Methods'),
        _table(
          ['Method (all sources combined)', 'Amount'],
          combined.entries.map((e) => [e.key, _money.format(e.value)]).toList(),
          flex: [4, 2],
        ),
        pw.SizedBox(height: 4),
        _statLine('Total', 'Tsh ${_money.format(combinedTotal)}', bold: true),
        pw.SizedBox(height: 10),
        pw.Row(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            categoryColumn('Sales', report.salesByPaymentMethod, 'No sales today.'),
            pw.SizedBox(width: 16),
            categoryColumn('Services', report.servicesByPaymentMethod, 'No services today.'),
          ],
        ),
        pw.SizedBox(height: 10),
        pw.Row(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            categoryColumn('Debt Repayments', report.repaymentsByPaymentMethod, 'No repayments today.'),
            pw.SizedBox(width: 16),
            categoryColumn('Other Income', report.otherIncomeByPaymentMethod, 'No other income today.'),
          ],
        ),
      ],
    );
  }

  static pw.Widget _productMovementSection(DailyReport report) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('Product Movement'),
        if (report.productMovement.isEmpty)
          _emptyNote('No product movement today.')
        else
          _table(
            ['Product', 'Unit', 'Opening', 'Added', 'Adjusted', 'Sold', 'Expected Closing'],
            report.productMovement
                .map((p) => [
                      p.isWatchlisted ? '* ${p.name}' : p.name,
                      p.unit.isEmpty ? '-' : p.unit,
                      '${p.opening}',
                      '${p.added}',
                      p.adjustment == 0 ? '-' : '${p.adjustment > 0 ? '+' : ''}${p.adjustment}',
                      '${p.sold}',
                      '${p.expectedClosing}',
                    ])
                .toList(),
            flex: [3, 2, 2, 2, 2, 2, 3],
          ),
        if (report.productMovement.any((p) => p.isWatchlisted))
          pw.Padding(
            padding: const pw.EdgeInsets.only(top: 4),
            child: pw.Text('* Watch-listed - see Stock Reconciliation below.', style: pw.TextStyle(fontSize: 8.5, color: _grey, fontStyle: pw.FontStyle.italic)),
          ),
        if (report.productMovement.any((p) => p.adjustment != 0 && p.adjustmentDetail != null))
          pw.Padding(
            padding: const pw.EdgeInsets.only(top: 6),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text('Adjustment details:', style: pw.TextStyle(fontSize: 8.5, color: _grey, fontWeight: pw.FontWeight.bold)),
                for (final p in report.productMovement.where((p) => p.adjustment != 0 && p.adjustmentDetail != null))
                  pw.Text('${p.name}: ${p.adjustmentDetail}', style: pw.TextStyle(fontSize: 8.5, color: _grey)),
              ],
            ),
          ),
      ],
    );
  }

  static pw.Widget _stockReconciliationSection(DailyReport report) {
    final watchlisted = report.productMovement.where((p) => p.isWatchlisted).toList();
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('Expected vs Physical Stock'),
        if (watchlisted.isEmpty)
          _emptyNote('No watch-listed products for this facility.')
        else if (report.status != 'submitted')
          _emptyNote('Physical counts have not been submitted yet.')
        else
          _table(
            ['Product', 'Expected', 'Physical', 'Difference', 'Status', 'Reason'],
            watchlisted.map((p) {
              final variance = p.variance ?? 0;
              final hasVariance = variance != 0;
              return [
                p.name,
                '${p.expectedClosing}',
                '${p.physicalCount ?? '-'}',
                hasVariance ? '${variance > 0 ? '+' : ''}$variance' : '0',
                hasVariance ? 'VARIANCE' : 'Match',
                hasVariance ? (p.varianceReason ?? '-') : '-',
              ];
            }).toList(),
            flex: [3, 2, 2, 2, 2, 3],
          ),
      ],
    );
  }

  static pw.Widget _debtSection(DailyReport report) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('Debt Activity'),
        _statLine('New debt today', 'Tsh ${_money.format(report.newDebtValue)}'),
        _statLine('Repayments collected', 'Tsh ${_money.format(report.repaymentsValue)}'),
        _statLine('Outstanding change', 'Tsh ${_money.format(report.outstandingChange)}', bold: true),
        pw.SizedBox(height: 6),
        if (report.clientDebtEntries.isEmpty)
          _emptyNote('No debt activity today.')
        else
          _table(
            ['Customer', 'Opening', 'New Debt', 'Repayment', 'Closing'],
            report.clientDebtEntries
                .map((c) => [
                      c.clientName,
                      _money.format(c.openingDebt),
                      _money.format(c.newDebt),
                      _money.format(c.repayment),
                      _money.format(c.closingDebt),
                    ])
                .toList(),
            flex: [3, 2, 2, 2, 2],
          ),
      ],
    );
  }

  static pw.Widget _expensesSection(DailyReport report) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('Expenses Recorded'),
        if (report.expenseLineItems.isEmpty)
          _emptyNote('No expenses recorded today.')
        else ...[
          _table(
            ['Time', 'Description', 'Category', 'Amount'],
            report.expenseLineItems.map((e) => [_time.format(e.time), e.description, e.category, _money.format(e.amount)]).toList(),
            flex: [2, 4, 3, 2],
          ),
          pw.SizedBox(height: 6),
          _statLine('Total Expenses', 'Tsh ${_money.format(report.totalExpenses)}', bold: true),
          if (report.totalOtherIncome > 0) _statLine('Other Income', 'Tsh ${_money.format(report.totalOtherIncome)}'),
        ],
      ],
    );
  }

  static pw.Widget _paymentReconciliationSection(DailyReport report) {
    if (report.paymentReconciliation.isEmpty) {
      return pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          _sectionTitle('Payment Reconciliation'),
          _emptyNote('No payments recorded today.'),
        ],
      );
    }
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('Payment Reconciliation'),
        for (final p in report.paymentReconciliation) ...[
          pw.Text(p.method, style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold, color: _deepGreen)),
          _statLine('Expected balance', 'Tsh ${_money.format(p.expected)}'),
          if (p.physicalCount != null) ...[
            _statLine('Physical balance counted', 'Tsh ${_money.format(p.physicalCount!)}', bold: true),
            _statLine(
              'Variance',
              (p.variance != null && p.variance != 0)
                  ? '${p.variance! > 0 ? '+' : ''}Tsh ${_money.format(p.variance!)} - VARIANCE'
                  : 'Tsh 0 - Match',
              bold: p.variance != null && p.variance != 0,
            ),
            if (p.variance != null && p.variance != 0 && (p.varianceReason ?? '').isNotEmpty)
              pw.Padding(
                padding: const pw.EdgeInsets.only(top: 2),
                child: pw.Text('Reason: ${p.varianceReason}', style: pw.TextStyle(fontSize: 9, color: _grey, fontStyle: pw.FontStyle.italic)),
              ),
          ] else if (!p.requiresCount)
            _emptyNote('No income via ${p.method} today - outflow only, no count needed.')
          else
            _emptyNote('Not yet submitted.'),
          if (p != report.paymentReconciliation.last) pw.SizedBox(height: 6),
        ],
      ],
    );
  }

  static pw.Widget _declarationSection(DailyReport report) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(border: pw.Border.all(color: PdfColors.grey400, width: 0.75), borderRadius: pw.BorderRadius.circular(4)),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text('Daily Closing Declaration', style: pw.TextStyle(fontSize: 10.5, fontWeight: pw.FontWeight.bold, color: _deepGreen)),
          pw.SizedBox(height: 4),
          pw.Text(
            report.declarationConfirmed
                ? "Confirmed: I have reviewed today's transactions and the cash and stock figures above "
                    'represent the closing figures for my shift.'
                : 'Not yet confirmed.',
            style: pw.TextStyle(fontSize: 9.5, color: report.declarationConfirmed ? _green : _red),
          ),
        ],
      ),
    );
  }

  static pw.Widget _signOffSection(DailyReport report) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text('Prepared by', style: pw.TextStyle(fontSize: 9, color: _grey)),
            pw.SizedBox(height: 2),
            pw.Text(report.generatedByName, style: pw.TextStyle(fontSize: 10.5, fontWeight: pw.FontWeight.bold)),
          ],
        ),
        pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text('Date / Time', style: pw.TextStyle(fontSize: 9, color: _grey)),
            pw.SizedBox(height: 2),
            pw.Text(
              report.submittedAt != null ? _dateTime.format(report.submittedAt!) : _dateTime.format(report.generatedAt),
              style: pw.TextStyle(fontSize: 10.5, fontWeight: pw.FontWeight.bold),
            ),
          ],
        ),
      ],
    );
  }
}
