// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhqVbHuMxirdg2K6CTr0FWfrNH7Ud5tQ8',
    appId: '1:1037378405744:web:1da5ab5b83372fa31cbbb5',
    messagingSenderId: '1037378405744',
    projectId: 'vetbiz-pro',
    authDomain: 'vetbiz-pro.firebaseapp.com',
    storageBucket: 'vetbiz-pro.firebasestorage.app',
    measurementId: 'G-JKZFJZYPGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDonH5fBDvzh8UPcFMfv-rIiBVpZLKdDGE',
    appId: '1:1037378405744:android:f1e571da606d3a5a1cbbb5',
    messagingSenderId: '1037378405744',
    projectId: 'vetbiz-pro',
    storageBucket: 'vetbiz-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrEtr3hiAKL5GneEtoGY6IFSt-t52Hx7o',
    appId: '1:1037378405744:ios:e14a1ee2725c4fd71cbbb5',
    messagingSenderId: '1037378405744',
    projectId: 'vetbiz-pro',
    storageBucket: 'vetbiz-pro.firebasestorage.app',
    iosBundleId: 'com.example.vetbizPro',
  );
}
